env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
builds:
  - main: cmd/kubenab/main.go
    binary: kubenab
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archive:
  format: tar.gz
  files:
    - LICENSE
checksum:
  name_template: 'checksums.txt'
